#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppWidgetListView.Resource", IsApplication=true)]

namespace AppWidgetListView
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Icon2 = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int widget_preview = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int XMLFile1 = 2130771971;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int d1 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int d2 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int d3 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int d4 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int d5 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int d6 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int d7 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int day1 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int day10 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int day11 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int day12 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int day13 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int day14 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int day15 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int day16 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int day17 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int day18 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int day19 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int day2 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int day20 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int day21 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int day22 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int day23 = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int day24 = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int day25 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int day26 = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int day27 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int day28 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int day29 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int day3 = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int day30 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int day31 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int day32 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int day33 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int day34 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int day35 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int day36 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int day37 = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int day38 = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int day39 = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int day4 = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int day40 = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int day41 = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int day42 = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int day5 = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int day6 = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int day7 = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int day8 = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int day9 = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int listViewWidget = 2130837555;
			
			// aapt resource value: 0x7F020000
			public const int MyButton = 2130837504;
			
			// aapt resource value: 0x7F020034
			public const int widgetBackground = 2130837556;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int list_row = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int widget = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int widget_layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040002
			public const int action_settings = 2130968578;
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int empty_string = 2130968580;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F040005
			public const int hello_world = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F060000
			public const int appwidgetprovider = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int widgetinfo = 2131099649;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
